global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['app:3000']
  #   metrics_path: '/metrics'
  #   scrape_interval: 5s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
