global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
