global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:3002']
    metrics_path: '/metrics'

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:3001']
    metrics_path: '/metrics'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
